### ISSUE TITLE
0.15 Beta 2: Wrong 360 Wireless Button Mapping

### ISSUE THREAD

**Issue by felixbuenemann** [d235j/360Controller#138] opened 2015-08-29 21:46 UTC
0.15 Beta 1 works fine with an original Wireless 360 Controller w/USB Dongle. But on 0.15 Beta 2 the DPad and most Buttons are recognized as DPad up, while the triggers and sticks are fine.

**Comment by FranticRain** [comment] 2015-08-29 21:50
This could be something with the remap functionality. It was just added to wireless 360 controllers in beta 2.

**Comment by RodrigoCard** [comment] 2015-08-31 17:56
I can confirm that. And when I try to remap, I get this:
![remap](https://cloud.githubusercontent.com/assets/417968/9585986/7a498a12-4ff0-11e5-929e-b40b0a3f6d2b.png)

Reseting the remap fixes that.

**Comment by RodrigoCard** [comment] 2015-08-31 18:01
@FranticRain could you look into that?

**Comment by FranticRain** [comment] 2015-08-31 18:15
I'll take a look at it, but I don't have any Xbox controllers on me right now, so it'll be a few days.

**Comment by Duros** [comment] 2015-09-06 15:20
I found that some game that native support the 360 controller have the start button the and right stick click mappen wrong, like Portal 2 and Lethal League. You have to press the right stick to get the start menu. I've got this with Beta 1 & 2.

**Comment by FranticRain** [comment] 2015-09-07 21:37
The original issue here is another settings bug. The default binding setup isn't loaded in through settings, causing all buttons to be bound to the 0th button, aka the d-pad up. I can do a couple things here. 1. Nothing. We really need to fix that settings bug. 2. Load the default mapping when the settings fail to load. This one is questionable because the only place to check it will be in the button press loop. And we would be adding a bunch of new cycles to every button press event. Something I would rather avoid. 3. I can disable rebinding of the Wireless 360 Controller until we fix the settings bug.

**Comment by RodrigoCard** [comment] 2015-09-07 21:54
3 is reasonable while we can't fix the settings bug, if possible.

Any ideas for the settings bug?

By the way, do you know why the wireless controller behaves differently
than wired one regarding this mapping issue?


Em segunda-feira, 7 de setembro de 2015, Drew Mills <
notifications@github.com> escreveu:

> The original issue here is another settings bug. The default binding setup
> isn't loaded in through settings, causing all buttons to be bound to the
> 0th button, aka the d-pad up. I can do a couple things here. 1. Nothing. We
> really need to fix that settings bug. 2. Load the default mapping when the
> settings fail to load. This one is questionable because the only place to
> check it will be in the button press loop. And we would be adding a bunch
> of new cycles to every button press event. Something I would rather avoid.
> 3. I can disable rebinding of the Wireless 360 Controller until we fix the
> settings bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/d235j/360Controller/issues/138#issuecomment-138381569>
> .
>


-- 
Enviado do Gmail para celular

**Comment by FranticRain** [comment] 2015-09-07 22:03
I've tried looking at that settings stuff before, and even looked for different ways to implement it. The real problem is that all of that stuff is so cryptic and horribly documented that I can't get any sort of grasp on it. As for the differences, I'm not sure why, but the properties of the wired controllers have their setProperties wireless controller's setProperties isn't. I don't know why it happens.

**Comment by Xelnath** [comment] 2015-09-12 09:32
I'm having this issue too. Pretty punishing - is there a workaround?

**Comment by RodrigoCard** [comment] 2015-09-15 18:03
ok, worked around https://github.com/d235j/360Controller/releases/tag/v0.15_beta3_unofficial

**Closed by RodrigoCard** 2015-09-15 18:03 UTC
Labels: bug
