### ISSUE TITLE
OSX Won't Sleep While Controller Is Plugged In

### ISSUE THREAD

**Issue by BakaNode** [d235j/360Controller#135] opened 2015-08-26 02:19 UTC
If I leave my controller plugged into my iMac (currently running 10.10.5) the system will never kick over to screensaver/display sleep mode. Upon unplugging the controller normal screensaver/sleep functions resume.

**Comment by RodrigoCard** [comment] 2015-08-26 21:56
duplicate of #59 , thanks for the report.

**Closed by RodrigoCard** 2015-08-26 21:56 UTC
