### ISSUE TITLE
XB360 Mortal Kombat FightStick Doesn't Work

### ISSUE THREAD

**Issue by rmclain** [d235j/360Controller#14] opened 2014-10-12 20:57 UTC
Hi any reason why the **XB360 Mortal Kombat FightStick** isn't detected by the PrefPane?  I've added it to the info.plist and recompiled but still doesn't show up.  Any help would be great.  Trying to build a Mac mini cade.

	XB360 Mortal Kombat FightStick:
	
	  Product ID:	0xf906
	  Vendor ID:	0x1bad
	  Version:	1.00
	  Serial Number:	2370656
	  Speed:	Up to 12 Mb/sec
	  Manufacturer:	Performance Designed Products
	  Location ID:	0x14100000 / 8
	  Current Available (mA):	500
	  Current Required (mA):	Unknown (Device has not been configured)

I've also tried running the following command

	sudo /Library/PreferencePanes/Pref360Control.prefPane/Contents/Resources/DriverTool \
	edit \
	XB360MortalKombatFightStick 7085 63750 \

![screen shot](http://cl.ly/image/3M2z3k2s3C2R/Screen%20Shot%202014-10-12%20at%204.55.32%20PM.png)

**Comment by RodrigoCard** [comment] 2015-02-03 00:45
I added that device to the list. Please test and tell us the results so we can close this issue:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview3.pkg

Cheers!

**Comment by RodrigoCard** [comment] 2015-02-14 23:11
@rmclain did you see the update?

**Comment by RodrigoCard** [comment] 2015-02-22 22:55
Does anyone have a Mortal Kombat FightStick to help use testing this?
The latest preview build can be downloaded here:
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview4.pkg

if there is no feedback or if someone tell us that succeeded in using this game controller with this driver, I will close this issue soon to clean the issue list for the next release.

Cheers!

**Closed** 2015-02-26 17:09 UTC
Labels: awating response, new device

**Comment by rmclain** [comment] 2015-03-02 04:19
@RodrigoCard Thanks for the update!  This fixed the issue and the controller now works flawlessly.  Really appreciated.  

Just a heads up to anyone else with this arcade stick, cheap cables will just flash the green circle around the xbox logo and it will never show up correctly in System Preferences, but worked like a champ with a decent usb cable.

**Comment by FranticRain** [comment] 2015-03-02 04:23
The cable issue is caused by using what is known as a "charge" cable instead of a "data" cable. Charge cables are just cheap cables that don't transfer any data. So you were sending power to your fight stick really well at least!
