### ISSUE TITLE
How to uninstall the driver?

### ISSUE THREAD

**Issue by mishafeingold** [d235j/360Controller#104] opened 2015-05-23 04:08 UTC
How do you remove the driver? I installed using the dmg package. I'm using Yosemite.

**Comment by RodrigoCard** [comment] 2015-05-23 18:47
hello,

this latest preview build of the driver supports self-uninstallation AND can be disabled temporarily (maybe you need this for a specific game?)
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg
(you may need to restart once)

a proper beta will be released soon

cheers!

**Comment by RodrigoCard** [comment] 2015-05-23 18:48
duplicate of #98

**Closed by RodrigoCard** 2015-05-23 18:47 UTC

**Comment by mishafeingold** [comment] 2015-06-01 21:31
Thank you!
